FUNCTION Main()
    QOut("=======================")
    QOut(" FICHA DE APRESENTAÇÃO ")
    Qout("======================")
    Qout("Nome: Lívia Ghirardi")
    Qout("Cidade: Sorocaba")
    Qout("Curso: Harbour/ADVPL")
    Qout("======================")
RETURN NIL
FUNCTION Main()
    QOut("=======================")
    QOut(" FICHA DE APRESENTAÇÃO ")
    Qout("======================")
    Qout("Nome: Lívia Ghirardi")
    Qout("Cidade: Sorocaba")
    Qout("Curso: Harbour/ADVPL")
    Qout("======================")
RETURN NIL